# -*- coding: utf-8 -*-
"""Equity_Valuation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MALDPa1hoakEKpfMueRg9sZRNrogREXx
"""

import numpy as np
import pandas as pd
import yfinance as yf
import warnings
from datetime import datetime
import os
warnings.filterwarnings('ignore')

class DCFValuation:
    """
    DCF估值模型类 - 直接从yfinance获取WACC
    """

    def __init__(self, ticker, perpetual_growth_rate=0.025):
        """
        初始化DCF模型
        """
        self.ticker = ticker
        self.perpetual_growth_rate = perpetual_growth_rate
        self.financial_data = None
        self.forecast_period = 5
        self.valuation_results = {}

        # 初始化所有必要的属性
        self.wacc = 0.085  # 默认WACC

        print("=== DCF估值模型初始化 ===")
        print(f"目标公司: {ticker}")
        print(f"永续增长率: {perpetual_growth_rate:.2%}")

    def validate_ticker(self):
        """
        验证股票代码是否存在
        """
        try:
            stock = yf.Ticker(self.ticker)
            # 尝试获取基本信息来验证股票代码
            info = stock.info
            if not info:
                print(f"[X] 股票代码 {self.ticker} 不存在或无法获取数据")
                return False

            # 尝试获取历史数据
            hist = stock.history(period="1mo")
            if hist.empty:
                print(f"[X] 股票代码 {self.ticker} 没有可用的历史数据")
                return False

            print(f"[OK] 股票代码 {self.ticker} 验证通过")
            return True

        except Exception as e:
            print(f"[X] 股票代码验证失败: {e}")
            return False

    def get_wacc_from_yfinance(self):
        """
        从yfinance获取WACC数据
        """
        print(f"\n=== 步骤1: 获取WACC ===")

        try:
            # 验证股票代码
            if not self.validate_ticker():
                print("使用默认WACC继续估值")
                return True

            # 获取公司信息
            stock = yf.Ticker(self.ticker)
            info = stock.info

            # 尝试从yfinance获取WACC
            # 注意: yfinance不直接提供WACC，但我们可以获取相关数据
            # 如果无法获取，使用行业平均或默认值

            # 尝试获取相关估值指标
            beta = info.get('beta', 1.0)
            current_price = info.get('currentPrice', 0)
            market_cap = info.get('marketCap', 0)
            total_debt = info.get('totalDebt', 0)
            total_cash = info.get('totalCash', 0)

            # 获取无风险利率（使用10年期美债收益率）
            try:
                treasury = yf.Ticker("^TNX")
                treasury_data = treasury.history(period="1mo")
                if not treasury_data.empty:
                    risk_free_rate = treasury_data['Close'].iloc[-1] / 100
                else:
                    risk_free_rate = 0.04  # 默认4%
            except:
                risk_free_rate = 0.04  # 默认4%

            # 市场风险溢价假设
            market_risk_premium = 0.055  # 5.5% 市场风险溢价

            # 计算股权成本 (使用CAPM)
            cost_of_equity = risk_free_rate + beta * market_risk_premium

            # 估算债务成本
            cost_of_debt = risk_free_rate + 0.02  # 假设比无风险利率高2%

            # 计算资本结构权重
            equity_value = market_cap
            debt_value = total_debt

            total_capital = equity_value + debt_value
            if total_capital > 0:
                weight_equity = equity_value / total_capital
                weight_debt = debt_value / total_capital
            else:
                weight_equity = 1.0
                weight_debt = 0.0

            # 公司税率
            tax_rate = 0.25  # 假设25%公司税率

            # 计算WACC
            if total_capital > 0:
                wacc = (weight_equity * cost_of_equity +
                       weight_debt * cost_of_debt * (1 - tax_rate))
            else:
                wacc = cost_of_equity  # 如果没有债务，WACC等于股权成本

            self.wacc = wacc

            # 保存WACC计算详情用于导出
            self.wacc_details = {
                'risk_free_rate': risk_free_rate,
                'beta': beta,
                'market_risk_premium': market_risk_premium,
                'cost_of_equity': cost_of_equity,
                'cost_of_debt': cost_of_debt,
                'debt_value': debt_value,
                'equity_value': equity_value,
                'weight_equity': weight_equity,
                'weight_debt': weight_debt,
                'tax_rate': tax_rate
            }

            print("[OK] WACC获取/计算完成")
            print(f"无风险利率: {risk_free_rate:.2%}")
            print(f"Beta系数: {beta:.4f}")
            print(f"市场风险溢价: {market_risk_premium:.2%}")
            print(f"股权成本: {cost_of_equity:.2%}")
            print(f"债务成本: {cost_of_debt:.2%}")
            print(f"WACC: {wacc:.2%}")

            return True

        except Exception as e:
            print(f"[X] WACC获取失败: {e}")
            # 使用默认WACC
            self.wacc = 0.085
            print(f"使用默认WACC: {self.wacc:.2%}")
            return True

    def fetch_financial_data(self):
        """
        获取财务数据
        """
        print(f"\n=== 步骤2: 获取财务数据 ===")

        try:
            stock = yf.Ticker(self.ticker)

            # 获取财务报表
            income_stmt = stock.financials
            balance_sheet = stock.balance_sheet
            cash_flow = stock.cashflow
            info = stock.info

            if income_stmt.empty:
                print("[X] 无法获取利润表数据，使用估算值")
                # 使用估算值继续
                self.revenue_ttm = 1e9  # 默认10亿美元营收
                self.net_income_ttm = 1e8  # 默认1亿美元净利润
                self.fcf_ttm = 8e7  # 默认8000万美元自由现金流
                self.revenue_growth = 0.15  # 默认15%增长率
                return True

            self.financial_data = {
                'income_stmt': income_stmt,
                'balance_sheet': balance_sheet,
                'cash_flow': cash_flow,
                'info': info
            }

            # 提取关键财务指标
            return self._extract_key_metrics()

        except Exception as e:
            print(f"[X] 财务数据获取失败: {e}")
            # 使用估算值继续
            self.revenue_ttm = 1e9  # 默认10亿美元营收
            self.net_income_ttm = 1e8  # 默认1亿美元净利润
            self.fcf_ttm = 8e7  # 默认8000万美元自由现金流
            self.revenue_growth = 0.15  # 默认15%增长率
            return True

    def _extract_key_metrics(self):
        """
        提取关键财务指标
        """
        try:
            income_stmt = self.financial_data['income_stmt']

            # 获取最新可用数据
            latest_year = income_stmt.columns[0]

            # 检查必要的财务指标是否存在
            required_metrics = ['Total Revenue', 'Net Income']
            for metric in required_metrics:
                if metric not in income_stmt.index:
                    print(f"[X] 缺少必要的财务指标: {metric}")
                    return False

            # 关键指标
            self.revenue_ttm = income_stmt.loc['Total Revenue', latest_year]
            self.net_income_ttm = income_stmt.loc['Net Income', latest_year]

            # 处理现金流数据
            cash_flow = self.financial_data['cash_flow']
            if not cash_flow.empty and 'Operating Cash Flow' in cash_flow.index:
                self.operating_cash_flow_ttm = cash_flow.loc['Operating Cash Flow', latest_year]
                if 'Capital Expenditure' in cash_flow.index:
                    self.capital_expenditure_ttm = abs(cash_flow.loc['Capital Expenditure', latest_year])
                else:
                    self.capital_expenditure_ttm = self.revenue_ttm * 0.05  # 默认5%的资本支出
            else:
                # 估算现金流
                self.operating_cash_flow_ttm = self.net_income_ttm * 1.2  # 假设现金流比净利润高20%
                self.capital_expenditure_ttm = self.revenue_ttm * 0.05

            # 计算自由现金流
            self.fcf_ttm = self.operating_cash_flow_ttm - self.capital_expenditure_ttm

            # 计算增长率（如果有多期数据）
            if len(income_stmt.columns) > 1:
                prev_year = income_stmt.columns[1]
                if 'Total Revenue' in income_stmt.index:
                    prev_revenue = income_stmt.loc['Total Revenue', prev_year]
                    if prev_revenue > 0:  # 避免除以零
                        self.revenue_growth = (self.revenue_ttm - prev_revenue) / prev_revenue
                    else:
                        self.revenue_growth = 0.15
                else:
                    self.revenue_growth = 0.15
            else:
                self.revenue_growth = 0.15

            print("[OK] 关键指标提取完成")
            print(f"最近营收: ${self.revenue_ttm/1e9:.2f}B")
            print(f"自由现金流(FCF): ${self.fcf_ttm/1e9:.2f}B")
            print(f"历史营收增长率: {self.revenue_growth:.2%}")

            return True

        except Exception as e:
            print(f"[X] 关键指标提取失败: {e}")
            return False

    def forecast_financials(self, custom_growth_rates=None):
        """
        预测未来财务数据

        Parameters:
        custom_growth_rates (list): 用户自定义的营收增长率列表
        """
        print(f"\n=== 步骤3: 财务预测 ===")

        try:
            # 使用用户提供的增长率或默认假设
            if custom_growth_rates and len(custom_growth_rates) == self.forecast_period:
                revenue_growth_rates = custom_growth_rates
                print("使用用户提供的营收增长率")
            else:
                # 默认预测假设（基于公司业务特点）
                revenue_growth_rates = [0.20, 0.18, 0.16, 0.14, 0.12]
                print("使用默认营收增长率")

            # 自由现金流利润率假设
            fcf_margins = [0.08, 0.09, 0.10, 0.11, 0.12]

            # 初始化预测数据框
            forecast_years = [f'Year_{i+1}' for i in range(self.forecast_period)]
            self.forecast_df = pd.DataFrame(index=forecast_years)

            # 基础数据
            base_revenue = self.revenue_ttm
            base_fcf = self.fcf_ttm

            # 预测各项指标
            revenues = []
            fcfs = []

            current_revenue = base_revenue
            for i in range(self.forecast_period):
                # 收入预测
                revenue_growth = revenue_growth_rates[i]
                next_revenue = current_revenue * (1 + revenue_growth)
                revenues.append(next_revenue)

                # 自由现金流预测
                fcf_margin = fcf_margins[i]
                next_fcf = next_revenue * fcf_margin
                fcfs.append(next_fcf)

                current_revenue = next_revenue

            # 存储预测结果
            self.forecast_df['Revenue'] = revenues
            self.forecast_df['FCF'] = fcfs
            self.forecast_df['Revenue_Growth'] = revenue_growth_rates
            self.forecast_df['FCF_Margin'] = fcf_margins

            print("[OK] 财务预测完成")
            for i, year in enumerate(forecast_years):
                print(f"{year}: 营收=${revenues[i]/1e9:.2f}B, FCF=${fcfs[i]/1e9:.2f}B, 增长率={revenue_growth_rates[i]:.1%}")

            return True

        except Exception as e:
            print(f"[X] 财务预测失败: {e}")
            return False

    def calculate_terminal_value(self):
        """
        计算终值
        """
        print(f"\n=== 步骤4: 终值计算 ===")

        try:
            # 最后一年自由现金流
            final_year_fcf = self.forecast_df['FCF'].iloc[-1]

            # 检查WACC和永续增长率的合理性
            if self.wacc <= self.perpetual_growth_rate:
                print("[!] WACC必须大于永续增长率，自动调整永续增长率")
                self.perpetual_growth_rate = self.wacc - 0.01

            # 使用戈登增长模型计算终值
            self.terminal_value = (final_year_fcf * (1 + self.perpetual_growth_rate) /
                                  (self.wacc - self.perpetual_growth_rate))

            print(f"[OK] 终值计算完成")
            print(f"最后一年FCF: ${final_year_fcf/1e9:.2f}B")
            print(f"终值: ${self.terminal_value/1e9:.2f}B")

            return True

        except Exception as e:
            print(f"[X] 终值计算失败: {e}")
            return False

    def calculate_enterprise_value(self):
        """
        计算企业价值
        """
        print(f"\n=== 步骤5: 企业价值计算 ===")

        try:
            # 贴现显性预测期自由现金流
            discounted_fcfs = []
            for i, fcf in enumerate(self.forecast_df['FCF']):
                discount_factor = 1 / (1 + self.wacc) ** (i + 1)
                discounted_fcf = fcf * discount_factor
                discounted_fcfs.append(discounted_fcf)

            # 贴现终值
            terminal_discount_factor = 1 / (1 + self.wacc) ** self.forecast_period
            discounted_terminal_value = self.terminal_value * terminal_discount_factor

            # 计算企业价值
            self.pv_explicit_period = sum(discounted_fcfs)
            self.pv_terminal_value = discounted_terminal_value
            self.enterprise_value = self.pv_explicit_period + self.pv_terminal_value

            print("[OK] 企业价值计算完成")
            print(f"企业价值: ${self.enterprise_value/1e9:.2f}B")

            return True

        except Exception as e:
            print(f"[X] 企业价值计算失败: {e}")
            return False

    def calculate_equity_value(self):
        """
        计算股权价值
        """
        print(f"\n=== 步骤6: 股权价值计算 ===")

        try:
            stock = yf.Ticker(self.ticker)
            info = stock.info

            # 获取当前财务数据，提供默认值
            cash = info.get('totalCash', self.enterprise_value * 0.1)  # 默认10%的企业价值
            debt = info.get('totalDebt', self.enterprise_value * 0.2)  # 默认20%的企业价值
            minority_interest = info.get('minorityInterest', 0)

            # 计算股权价值
            self.equity_value = (self.enterprise_value - debt + cash - minority_interest)

            # 获取总股本
            shares_outstanding = info.get('sharesOutstanding', self.equity_value / 100)  # 默认股价$100

            # 计算每股价值
            self.value_per_share = self.equity_value / shares_outstanding

            # 获取当前股价用于比较
            current_price = info.get('currentPrice', 0)
            if current_price == 0:
                # 如果无法获取当前股价，使用历史数据
                hist = stock.history(period="1mo")
                if not hist.empty:
                    current_price = hist['Close'].iloc[-1]
                else:
                    current_price = self.value_per_share * 0.8  # 默认低估20%

            self.valuation_results = {
                'enterprise_value': self.enterprise_value,
                'equity_value': self.equity_value,
                'value_per_share': self.value_per_share,
                'current_price': current_price,
                'premium_discount': (self.value_per_share - current_price) / current_price,
                'cash': cash,
                'debt': debt,
                'shares_outstanding': shares_outstanding,
                'wacc': self.wacc
            }

            print("[OK] 股权价值计算完成")
            print(f"每股价值: ${self.value_per_share:.2f}")
            print(f"当前股价: ${current_price:.2f}")

            return True

        except Exception as e:
            print(f"[X] 股权价值计算失败: {e}")
            return False

    def sensitivity_analysis(self):
        """
        敏感性分析
        """
        print(f"\n=== 步骤7: 敏感性分析 ===")

        try:
            # 测试不同的WACC和永续增长率组合
            wacc_range = [self.wacc - 0.01, self.wacc, self.wacc + 0.01]
            growth_range = [self.perpetual_growth_rate - 0.005,
                           self.perpetual_growth_rate,
                           self.perpetual_growth_rate + 0.005]

            sensitivity_matrix = pd.DataFrame(index=[f'{g:.1%}' for g in growth_range],
                                             columns=[f'{w:.1%}' for w in wacc_range])

            current_share_price = self.valuation_results['current_price']
            final_year_fcf = self.forecast_df['FCF'].iloc[-1]

            for i, growth in enumerate(growth_range):
                for j, wacc in enumerate(wacc_range):
                    # 确保WACC > 增长率
                    if wacc <= growth:
                        share_value = 0  # 无效组合
                    else:
                        # 重新计算终值和企业价值
                        terminal_value = (final_year_fcf * (1 + growth) / (wacc - growth))

                        # 贴现显性期现金流
                        discounted_fcfs = 0
                        for idx, fcf in enumerate(self.forecast_df['FCF']):
                            discount_factor = 1 / (1 + wacc) ** (idx + 1)
                            discounted_fcfs += fcf * discount_factor

                        # 贴现终值
                        discounted_terminal = terminal_value / (1 + wacc) ** self.forecast_period

                        enterprise_value = discounted_fcfs + discounted_terminal
                        equity_value = enterprise_value - self.valuation_results['debt'] + self.valuation_results['cash']
                        share_value = equity_value / self.valuation_results['shares_outstanding']

                    sensitivity_matrix.iloc[i, j] = share_value

            self.sensitivity_matrix = sensitivity_matrix.astype(float)

            print("[OK] 敏感性分析完成")
            print("\n每股价值敏感性分析矩阵:")
            print(sensitivity_matrix.round(2))

            return True

        except Exception as e:
            print(f"[X] 敏感性分析失败: {e}")
            return False

    def export_to_excel(self, filename=None):
        """
        将估值结果导出到Excel文件
        """
        print(f"\n=== 步骤8: 导出Excel文件 ===")

        try:
            # 生成默认文件名
            if filename is None:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                filename = f"{self.ticker}_DCF_valuation_{timestamp}.xlsx"

            # 创建Excel写入器
            with pd.ExcelWriter(filename, engine='openpyxl') as writer:

                # 1. 估值结果汇总表
                summary_data = {
                    '指标': [
                        '公司代码', '估值日期', 'DCF估值(每股)', '当前股价',
                        '估值差异', '投资建议', 'WACC', '永续增长率', '预测期(年)',
                        '企业价值', '股权价值', '现金', '债务', '总股本'
                    ],
                    '数值': [
                        self.ticker,
                        datetime.now().strftime("%Y-%m-%d"),
                        f"${self.valuation_results['value_per_share']:.2f}",
                        f"${self.valuation_results['current_price']:.2f}",
                        f"{self.valuation_results['premium_discount']:+.2%}",
                        self._get_investment_recommendation(),
                        f"{self.valuation_results['wacc']:.2%}",
                        f"{self.perpetual_growth_rate:.2%}",
                        self.forecast_period,
                        f"${self.valuation_results['enterprise_value']/1e9:.2f}B",
                        f"${self.valuation_results['equity_value']/1e9:.2f}B",
                        f"${self.valuation_results['cash']/1e9:.2f}B",
                        f"${self.valuation_results['debt']/1e9:.2f}B",
                        f"{self.valuation_results['shares_outstanding']/1e9:.2f}B股"
                    ]
                }
                summary_df = pd.DataFrame(summary_data)
                summary_df.to_excel(writer, sheet_name='估值汇总', index=False)

                # 2. 财务预测表
                if hasattr(self, 'forecast_df'):
                    forecast_export = self.forecast_df.copy()
                    forecast_export['Revenue'] = forecast_export['Revenue'] / 1e9  # 转换为十亿美元
                    forecast_export['FCF'] = forecast_export['FCF'] / 1e9  # 转换为十亿美元
                    forecast_export['Revenue_Growth'] = forecast_export['Revenue_Growth'].apply(lambda x: f"{x:.1%}")
                    forecast_export['FCF_Margin'] = forecast_export['FCF_Margin'].apply(lambda x: f"{x:.1%}")
                    forecast_export.rename(columns={
                        'Revenue': '营收(十亿美元)',
                        'FCF': '自由现金流(十亿美元)',
                        'Revenue_Growth': '营收增长率',
                        'FCF_Margin': 'FCF利润率'
                    }, inplace=True)
                    forecast_export.to_excel(writer, sheet_name='财务预测')

                # 3. WACC计算详情
                if hasattr(self, 'wacc_details'):
                    wacc_data = {
                        '参数': [
                            '无风险利率', 'Beta系数', '市场风险溢价', '股权成本',
                            '债务成本', '债务价值', '股权价值', '债务权重', '股权权重', '公司税率'
                        ],
                        '数值': [
                            f"{self.wacc_details['risk_free_rate']:.2%}",
                            f"{self.wacc_details['beta']:.4f}",
                            f"{self.wacc_details['market_risk_premium']:.2%}",
                            f"{self.wacc_details['cost_of_equity']:.2%}",
                            f"{self.wacc_details['cost_of_debt']:.2%}",
                            f"${self.wacc_details['debt_value']/1e9:.2f}B",
                            f"${self.wacc_details['equity_value']/1e9:.2f}B",
                            f"{self.wacc_details['weight_debt']:.2%}",
                            f"{self.wacc_details['weight_equity']:.2%}",
                            f"{self.wacc_details['tax_rate']:.1%}"
                        ]
                    }
                    wacc_df = pd.DataFrame(wacc_data)
                    wacc_df.to_excel(writer, sheet_name='WACC计算', index=False)

                # 4. 敏感性分析表
                if hasattr(self, 'sensitivity_matrix'):
                    sensitivity_export = self.sensitivity_matrix.copy()
                    sensitivity_export.rename(
                        index={idx: f'永续增长率 {idx}' for idx in sensitivity_export.index},
                        columns={col: f'WACC {col}' for col in sensitivity_export.columns},
                        inplace=True
                    )
                    sensitivity_export = sensitivity_export.applymap(lambda x: f"${x:.2f}")
                    sensitivity_export.to_excel(writer, sheet_name='敏感性分析')

                # 5. DCF计算过程
                if hasattr(self, 'terminal_value') and hasattr(self, 'enterprise_value'):
                    dcf_calc_data = {
                        '项目': [
                            '终值', '终值现值', '显性期现值', '企业价值',
                            '现金', '债务', '少数股东权益', '股权价值'
                        ],
                        '数值(十亿美元)': [
                            self.terminal_value / 1e9,
                            self.pv_terminal_value / 1e9,
                            self.pv_explicit_period / 1e9,
                            self.enterprise_value / 1e9,
                            self.valuation_results['cash'] / 1e9,
                            self.valuation_results['debt'] / 1e9,
                            0,  # 少数股东权益，这里简化处理
                            self.valuation_results['equity_value'] / 1e9
                        ]
                    }
                    dcf_calc_df = pd.DataFrame(dcf_calc_data)
                    dcf_calc_df['数值(十亿美元)'] = dcf_calc_df['数值(十亿美元)'].apply(lambda x: f"${x:.2f}")
                    dcf_calc_df.to_excel(writer, sheet_name='DCF计算过程', index=False)

            print(f"[OK] Excel文件导出成功: {filename}")
            print(f"文件包含以下工作表:")
            print("  - 估值汇总: 主要估值结果和投资建议")
            print("  - 财务预测: 未来5年财务预测")
            print("  - WACC计算: WACC计算详情")
            print("  - 敏感性分析: 不同假设下的估值敏感性")
            print("  - DCF计算过程: DCF估值详细计算过程")

            return True

        except Exception as e:
            print(f"[X] Excel文件导出失败: {e}")
            return False

    def _get_investment_recommendation(self):
        """
        获取投资建议
        """
        premium = self.valuation_results['premium_discount']

        if premium > 0.1:
            return "强烈买入"
        elif premium > 0.05:
            return "买入"
        elif premium > -0.05:
            return "持有"
        elif premium > -0.1:
            return "卖出"
        else:
            return "强烈卖出"

    def comprehensive_valuation(self, custom_growth_rates=None):
        """
        执行完整估值流程
        """
        print("=" * 60)
        print(f"{self.ticker} DCF估值分析")
        print("=" * 60)

        # 执行所有估值步骤
        steps = [
            ("WACC获取", self.get_wacc_from_yfinance),
            ("财务数据获取", self.fetch_financial_data),
            ("财务预测", lambda: self.forecast_financials(custom_growth_rates)),
            ("终值计算", self.calculate_terminal_value),
            ("企业价值计算", self.calculate_enterprise_value),
            ("股权价值计算", self.calculate_equity_value),
            ("敏感性分析", self.sensitivity_analysis)
        ]

        # 执行步骤
        for step_name, step_func in steps:
            print(f"\n>> 执行: {step_name}")
            result = step_func()
            # 明确检查返回值是否为True
            if result is True:
                continue
            elif step_name in ["敏感性分析"]:
                print(f"! {step_name} 跳过，继续后续分析")
                continue
            else:
                print(f"X 估值中断于: {step_name}")
                return None

        # 输出最终结论
        self._print_valuation_conclusion()

        return self.valuation_results

    def _print_valuation_conclusion(self):
        """
        输出估值结论
        """
        print("\n" + "=" * 60)
        print("估值结论汇总")
        print("=" * 60)

        if hasattr(self, 'valuation_results'):
            current_price = self.valuation_results['current_price']
            dcf_value = self.valuation_results['value_per_share']
            premium = self.valuation_results['premium_discount']
            wacc = self.valuation_results['wacc']

            print(f"DCF估值结果: ${dcf_value:.2f}")
            print(f"当前市场价格: ${current_price:.2f}")
            print(f"估值差异: {premium:+.2%}")

            recommendation = self._get_investment_recommendation()
            print(f"投资建议: {recommendation}")
            print(f"\n关键假设:")
            print(f"- WACC: {wacc:.2%} (基于yfinance数据)")
            print(f"- 永续增长率: {self.perpetual_growth_rate:.2%}")
            print(f"- 预测期: {self.forecast_period}年")

            if hasattr(self, 'forecast_df'):
                print(f"- 平均营收增长率: {np.mean(self.forecast_df['Revenue_Growth']):.1%}")
                print(f"- 平均FCF利润率: {np.mean(self.forecast_df['FCF_Margin']):.1%}")

def get_user_input():
    """
    获取用户输入
    """
    print("=== DCF估值模型用户界面 ===")
    print("请输入以下信息进行公司估值分析:")

    # 常见股票代码示例
    print("\n常见股票代码示例:")
    print("  - 苹果: AAPL")
    print("  - 特斯拉: TSLA")
    print("  - 微软: MSFT")
    print("  - 亚马逊: AMZN")
    print("  - 谷歌: GOOGL")
    print("  - 纳斯达克: NDAQ (注意: NASDAQ交易所的代码是NDAQ, 不是NASDQ)")

    # 获取公司代码
    while True:
        ticker = input("\n1. 请输入公司股票代码 (例如: TSLA): ").strip().upper()
        if ticker:
            # 验证股票代码格式
            if len(ticker) < 2 or len(ticker) > 10:
                print("股票代码长度应在2-10个字符之间，请重新输入")
                continue
            break
        print("股票代码不能为空，请重新输入")

    # 获取永续增长率
    while True:
        growth_input = input("\n2. 请输入永续增长率 (例如: 0.025 表示2.5%，默认: 0.025): ").strip()
        if not growth_input:
            perpetual_growth = 0.025
            break
        try:
            perpetual_growth = float(growth_input)
            if 0 < perpetual_growth < 0.1:  # 合理范围检查
                break
            else:
                print("永续增长率应在0和0.1之间，请重新输入")
        except ValueError:
            print("请输入有效的数字，例如: 0.025")

    # 获取自定义营收增长率
    custom_growth_rates = None
    use_custom = input("\n3. 是否使用自定义营收增长率? (y/n，默认: n): ").strip().lower()
    if use_custom == 'y':
        print("请输入未来5年的营收增长率 (每年一个，用逗号分隔，例如: 0.25,0.20,0.18,0.15,0.12)")
        while True:
            growth_input = input("营收增长率: ").strip()
            try:
                rates = [float(x.strip()) for x in growth_input.split(',')]
                if len(rates) == 5 and all(0 <= r < 1 for r in rates):
                    custom_growth_rates = rates
                    break
                else:
                    print("必须输入5个介于0和1之间的数字，请重新输入")
            except ValueError:
                print("请输入有效的数字，用逗号分隔")

    return ticker, perpetual_growth, custom_growth_rates

def main():
    """
    主函数 - 用户友好的DCF估值流程
    """
    print("欢迎使用DCF估值模型!")
    print("本工具将基于yfinance数据自动计算WACC并使用贴现现金流方法对公司进行估值")
    print("=" * 60)

    # 获取用户输入
    ticker, perpetual_growth, custom_growth_rates = get_user_input()

    # 创建DCF估值模型
    dcf = DCFValuation(
        ticker=ticker,
        perpetual_growth_rate=perpetual_growth
    )

    # 执行估值
    print("\n" + "=" * 60)
    print("开始估值分析...")
    print("=" * 60)

    results = dcf.comprehensive_valuation(custom_growth_rates)

    # 输出最终结果
    print("\n" + "=" * 60)
    print("估值完成!")
    print("=" * 60)

    if results:
        print(f"\n公司: {ticker}")
        print(f"DCF估值: ${results['value_per_share']:.2f}")
        print(f"当前股价: ${results['current_price']:.2f}")
        print(f"估值差异: {results['premium_discount']:+.2%}")
        print(f"计算出的WACC: {results['wacc']:.2%}")

        # 询问是否导出Excel
        export_excel = input("\n是否将结果导出为Excel文件? (y/n): ").strip().lower()
        if export_excel == 'y':
            filename = input("请输入文件名 (可选，直接回车使用默认名称): ").strip()
            if not filename:
                filename = None
            dcf.export_to_excel(filename)

    print("\n" + "=" * 60)
    print("风险提示:")
    print("1. DCF估值对假设非常敏感")
    print("2. WACC基于yfinance数据估算，可能不反映未来情况")
    print("3. 实际结果可能因假设变化而大幅波动")
    print("4. 建议结合其他估值方法综合判断")
    print("=" * 60)

    # 询问是否进行另一次估值
    while True:
        again = input("\n是否进行另一次估值? (y/n): ").strip().lower()
        if again == 'y':
            main()
            break
        elif again == 'n':
            print("感谢使用DCF估值模型!")
            break
        else:
            print("请输入 y 或 n")

# 运行主程序
if __name__ == "__main__":
    main()